### ISSUE TITLE
Junglenet 2 지원여부

### ISSUE THREAD

**Issue by sunghwanJo** [EOSNOVA/Auth-SDK-ANDROID#1]
http://dev.cryptolions.io:38888(jungle1) 이 deprecated 되었는데, jungle2.cryptolions.io (jungle2) 지원 해주실 수 있나요?

**Comment by shinhyo** [comment]
https://github.com/EOSNOVA/Auth-SDK-ANDROID/blob/master/apk/nova_testnet_2.apk
jungle2.cryptolions.io 를 테스트 할 수 있습니다!

노바월렛에서 테스트넷 노드를 추가하는 방식이 예정되어 있습니다.
감사합니다.
